# Railway config for a single-service Vite (React) frontend
# Place at repo root as `railway.toml`

[build]
builder = "NIXPACKS"

[deploy]
# Build the production bundle in /dist
buildCommand = "npm ci && npm run build"

# Serve the built files. Using Vite preview binds to $PORT.
startCommand = "npm run preview"
healthcheckPath = "/index.html"
