# railway.toml — Frontend (React + Vite) on Railway
# Serves your production build using `serve`, binding to Railway's $PORT

[build]
builder = "NIXPACKS"

[deploy]
# Use npm install if you don't have a package-lock.json; otherwise use npm ci
buildCommand = "npm install && npm run build"
startCommand = "npm run start"
healthcheckPath = "/index.html"